[location]
path = "../../../post_processing/data/music/"
overwrite = "true"

[data]
rec_filename = "ambar_fold1_BPR_test_recommendations.csv"
feature_filename = "ambar_items.csv"

[output]
filename = "ambar_fold1_BPR_LLM.csv_weighted_scoring_product_lottery_0.2_fold1.json"
dnc = "true"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 500

[context]
context_class = "csv_context"

[choice]
choice_class = "weighted_scoring"

[post]
postprocess_class = "null"

[allocation]
allocation_class = "product_lottery"

[context.properties]
compatibility_file = "ambar_llm_compat.csv"
popularity_data = "popularity_ambar.csv"

[choice.properties]
recommender_weight = 0.2

[feature.one]
name = "llm_individual"
protected_feature = "consumer_individual"
protected_values = [ 1,]

[feature.two]
name = "female"
protected_feature = "female"
protected_values = [ 1,]

[agent.one]
name = "llm_individual"
metric_class = "llm_fairness"
compatibility_class = "context_compatibility"
preference_function_class = "llm_preference"

[agent.two]
name = "female"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[allocation.properties]

[agent.one.metric]
prompt = "rank individual fairness based on how likely this user is to have good recommendations compared to how likely other users have had good recommendations. The better this users recommendations are, the higher the afirness score should be"
model = "gpt-4.1-mini"

[agent.one.preference]
prompt = "boost scores for items you think this user is most likely to like"
model = "gpt-4.1-mini"

[agent.two.metric]
feature = "female"
proportion = 0.5

[agent.two.preference]
delta = 50
feature = "female"
